const mockApplicantsByJob = {
  J201: [
    {
      id: "C101",
      name: "Howard Anuron",
      score: 0.99,
      skills: [
        "Python",
        "SQL",
        "Pandas",
        "Machine Learning",
        "Statistics",
        "Data Visualization",
      ],
      highlights: ["Strong ML fundamentals", "Good SQL + analytics projects"],
    },
    {
      id: "C102",
      name: "Tanvir Hossain",
      score: 0.86,
      skills: ["Python", "Numpy", "Sklearn", "Feature Engineering", "Git"],
      highlights: ["Good coding", "Needs more production experience"],
    },
    {
      id: "C103",
      name: "Nusrat Jahan",
      score: 0.79,
      skills: ["SQL", "PowerBI", "Excel", "Reporting", "Communication"],
      highlights: ["Great BI", "Limited ML depth"],
    },
    {
      id: "C104",
      name: "Rahat Ahmed",
      score: 0.82,
      skills: ["Python", "SQL", "Statistics", "A/B Testing"],
      highlights: ["Strong analytics baseline", "Good experimentation habits"],
    },
    {
      id: "C105",
      name: "Mahira Khan",
      score: 0.8,
      skills: ["Python", "Machine Learning", "Feature Engineering", "Git"],
      highlights: ["Good model prototyping", "Needs deeper statistical rigor"],
    },
    {
      id: "C106",
      name: "Samiul Karim",
      score: 0.78,
      skills: ["SQL", "Python", "Data Visualization", "Communication"],
      highlights: ["Good storytelling", "Limited ML project depth"],
    },
  ],
  J202: [
    {
      id: "C201",
      name: "Siam Ahmed",
      score: 0.93,
      skills: ["Node.js", "REST API", "PostgreSQL", "Redis", "Docker", "CI/CD"],
      highlights: ["Solid backend", "Good system design"],
    },
    {
      id: "C202",
      name: "Farhan Kabir",
      score: 0.84,
      skills: ["Node.js", "Express", "MongoDB", "AWS", "Testing"],
      highlights: ["Good stack", "Needs more caching/scale work"],
    },
    {
      id: "C203",
      name: "Nayeem Hasan",
      score: 0.82,
      skills: ["Node.js", "Redis", "System Design", "Docker", "CI/CD"],
      highlights: ["Strong caching knowledge", "Good deployment discipline"],
    },
    {
      id: "C204",
      name: "Ruba Tasnim",
      score: 0.81,
      skills: ["Node.js", "REST API", "PostgreSQL", "Microservices"],
      highlights: ["Solid service design", "Needs more observability practice"],
    },
    {
      id: "C205",
      name: "Fardin Rahman",
      score: 0.79,
      skills: ["Express", "Redis", "System Design", "Kubernetes"],
      highlights: ["Good architecture sense", "Needs stronger CI/CD coverage"],
    },
    {
      id: "C206",
      name: "Nafisa Chowdhury",
      score: 0.78,
      skills: ["Node.js", "Microservices", "CI/CD", "AWS"],
      highlights: ["Good delivery flow", "Needs stronger DB optimization"],
    },
    {
      id: "C207",
      name: "Tanim Alvi",
      score: 0.77,
      skills: ["Node.js", "REST API", "Redis", "Testing"],
      highlights: ["Reliable API work", "Needs broader system design depth"],
    },
    {
      id: "C208",
      name: "Kawsar Iqbal",
      score: 0.76,
      skills: ["Node.js", "PostgreSQL", "Microservices", "Docker"],
      highlights: ["Good backend fundamentals", "Needs stronger caching strategy"],
    },
    {
      id: "C209",
      name: "Israt Jahan",
      score: 0.75,
      skills: ["Node.js", "CI/CD", "System Design", "Monitoring"],
      highlights: ["Good ops mindset", "Needs deeper API performance tuning"],
    },
    {
      id: "C210",
      name: "Ashikur Rahman",
      score: 0.74,
      skills: ["Express", "Redis", "PostgreSQL", "System Design"],
      highlights: ["Strong data layer", "Needs microservices exposure"],
    },
    {
      id: "C211",
      name: "Jannat Sultana",
      score: 0.73,
      skills: ["Node.js", "REST API", "Docker", "CI/CD"],
      highlights: ["Good execution speed", "Needs distributed system depth"],
    },
  ],
  J203: [
    {
      id: "C301",
      name: "Nabila Sultana",
      score: 0.89,
      skills: ["Figma", "UX Research", "Wireframing", "Prototyping", "Design Systems"],
      highlights: ["Strong portfolio", "Great research process"],
    },
    {
      id: "C302",
      name: "Arian Chowdhury",
      score: 0.86,
      skills: ["Figma", "Prototyping", "Design Systems", "Usability Testing"],
      highlights: ["Good interaction design", "Strong component thinking"],
    },
    {
      id: "C303",
      name: "Maisha Fairooz",
      score: 0.84,
      skills: ["UX Research", "Figma", "Journey Mapping", "Prototyping"],
      highlights: ["Research depth", "Clear design rationale"],
    },
    {
      id: "C304",
      name: "Rafiul Karim",
      score: 0.8,
      skills: ["Figma", "Visual Design", "Design Systems", "Accessibility"],
      highlights: ["Solid visual craft", "Needs more UX research breadth"],
    },
    {
      id: "C305",
      name: "Sumaiya Haque",
      score: 0.78,
      skills: ["Wireframing", "Prototyping", "Design Critique", "UX Research"],
      highlights: ["Fast prototyping", "Needs stronger design system experience"],
    },
  ],
  J204: [
    {
      id: "C401",
      name: "Mehedi Hasan",
      score: 0.92,
      skills: ["Python", "PyTorch", "Transformers", "NLP", "MLOps"],
      highlights: ["Hands-on with Transformers", "Good deployment basics"],
    },
    {
      id: "C402",
      name: "Sadia Islam",
      score: 0.81,
      skills: ["Python", "TensorFlow", "Text Processing", "Data Cleaning"],
      highlights: ["Good data pipeline", "Needs stronger modeling"],
    },
    {
      id: "C403",
      name: "Farzana Rahman",
      score: 0.85,
      skills: ["Python", "PyTorch", "Transformers", "MLOps"],
      highlights: ["Balanced NLP stack", "Good experiment tracking"],
    },
    {
      id: "C404",
      name: "Rakib Hasan",
      score: 0.83,
      skills: ["Python", "PyTorch", "Model Serving", "Docker"],
      highlights: ["Good deployment experience", "Needs deeper transformer tuning"],
    },
    {
      id: "C405",
      name: "Shaila Akter",
      score: 0.82,
      skills: ["Python", "Transformers", "Prompt Engineering", "NLP"],
      highlights: ["Strong NLP background", "Limited MLOps exposure"],
    },
    {
      id: "C406",
      name: "Nafis Alim",
      score: 0.79,
      skills: ["PyTorch", "Transformers", "MLOps", "Kubernetes"],
      highlights: ["Strong ops mindset", "Needs better data processing depth"],
    },
    {
      id: "C407",
      name: "Priya Sen",
      score: 0.78,
      skills: ["Python", "NLP", "Text Processing", "Evaluation"],
      highlights: ["Good text analytics", "Needs stronger production pipeline"],
    },
    {
      id: "C408",
      name: "Tanzeem Kabir",
      score: 0.77,
      skills: ["Python", "PyTorch", "Data Pipelines", "Airflow"],
      highlights: ["Great pipeline work", "Needs deeper transformer expertise"],
    },
    {
      id: "C409",
      name: "Mahin Islam",
      score: 0.76,
      skills: ["Transformers", "MLOps", "Monitoring", "CI/CD"],
      highlights: ["Good reliability focus", "Needs stronger modeling theory"],
    },
    {
      id: "C410",
      name: "Sabira Ahmed",
      score: 0.75,
      skills: ["Python", "PyTorch", "Feature Engineering", "NLP"],
      highlights: ["Good coding discipline", "Needs deployment maturity"],
    },
    {
      id: "C411",
      name: "Imran Mahmud",
      score: 0.74,
      skills: ["Python", "TensorFlow", "Transformers", "MLOps"],
      highlights: ["Cross-framework comfort", "Needs better PyTorch depth"],
    },
    {
      id: "C412",
      name: "Lamia Nahar",
      score: 0.73,
      skills: ["PyTorch", "NLP", "Experiment Tracking", "Docker"],
      highlights: ["Good reproducibility habits", "Needs stronger end-to-end serving"],
    },
    {
      id: "C413",
      name: "Zayan Iqbal",
      score: 0.72,
      skills: ["Python", "MLOps", "Data Versioning", "Model Deployment"],
      highlights: ["Strong ops orientation", "Needs deeper transformer knowledge"],
    },
  ],
};

export { mockApplicantsByJob };
